### ISSUE TITLE
大佬可不可以解释一下:  Exercise 3.11,  3.12,  3.13  怎么想的.

### ISSUE THREAD

**Issue by hyc6668378** [LyWangPX/Solutions-of-Reinforcement-Learning-An-Introduction-Sutton-2nd#1]

**Comment by LyWangPX** [comment]
谢谢你关注我的不知名的小github
第三章是我RL学习的起点，我需要回忆一下当时的情况，或许会有不少错误的产生，感谢你的指出。
我会在思考过后给你详尽答复。

**Comment by LyWangPX** [comment]
你好。

我认为3.11是我的计算错误。我忘了按a求和计算期待值，已经更新文档。
3.13 已经回忆不起来当时的思考方式，我写了最新的答案
至于3.12思路如下，如果有误希望你能指出：

3.12 
对于一个给定的策略pi来说在sate S的情况下，有很多a的可能性。这里单纯用q计算期待值即应等于v。要不要加gamma我已经记不清了。

谢谢你的指出

**Comment by hyc6668378** [comment]
多谢大佬~您的作业写的很棒.
您的解释我理解到了.
答案肯定没问题.
突然发现用59页的backup tree 用起来更清晰一些.(david silver 课上也提到过).
