### ISSUE TITLE
Exercise 3.5

### ISSUE THREAD

**Issue by zhiqipan** [LyWangPX/Solutions-of-Reinforcement-Learning-An-Introduction-Sutton-2nd#3]
I think exercise 3.5 should be redefining state set S instead of reward set R, because in episodic tasks, there are terminal states and it should also be included in the state set S, denoted as S+.

And for reward set, in either case, it's finite so there's no modification needed. So the (slight) modification is on the state set instead of reward set, in my humble opinion.

**Comment by LyWangPX** [comment]
Thanks, you are definitely right. 
I will modify the issue asap.

And, because there are so few people online reading this book, would you like to share your contacts with me? I personally find the book become deeper in the latter half and desire someone to discuss with. 

Thank you!

**Comment by zhiqipan** [comment]
Thanks for your reply. Sure absolutely, let me shoot you an email.

I also finished all exercises in Chp 3 recently, and found that there are some inconsistencies between the solutions of yours and mine, let's discuss together ;D
