### ISSUE TITLE
关于练习4.4

### ISSUE THREAD

**Issue by JUSTLOVELE** [LyWangPX/Solutions-of-Reinforcement-Learning-An-Introduction-Sutton-2nd#4]
您好，请问一下练习4.4的参考答案
      If old-action  not in {ai}, which is the all equi-best solutions from π(s), ......
我不是很明白这个a_i是什么意思，希望不吝赐教

**Comment by LyWangPX** [comment]
您好。

我想我指的是所有当前state下的同等最优解，也就是后面英文所形容的集合。

确实我的形容有些不清楚，很感谢你的指出。在这个月我会进行修改。

**Comment by JUSTLOVELE** [comment]
理解了，谢谢哈
